run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - docs
    - ui
    - .git

  exclude-files:
    - pkg/utils/terminal.go

linters:
  enable:
    - govet
    - staticcheck

output:
  format: colored-line-number